# If the $XDG_DATA_HOME env variable is set, then $XDG_DATA_HOME/pnpm/global


# prompt yes with golang automation

sudo pacman-mirrors --geoip

# :: Repository extra for ghidra
#    1) jdk-openjdk  2) jdk17-openjdk  3) jdk21-openjdk

sudo pacman -Syyu --needed alacritty base-devel bat btop cairo-dock cairo-dock-plug-ins discord fluent-reader git ghidra kitty keepassxc neovim nyxt obsidian python-pynvim postman-bin qbittorrent radare2 tldr unzip wezterm wireshark-qt
git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si

# rustup prompt
# 1) Proceed with standard installation (default - just press enter)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
sudo pacman -Rsn cups cups-pdf elisa gutenprint gwenview kate kcalc kdeconnect kfind khelpcenter kfind manjaro-hello manjaro-printer nano nano-syntax-highlighting skanlite system-config-printer vi yakuake
sudo pacman -Rsn $(sudo pacman -Qdtq)
yay -Syyu anki bruno conan imhex miniconda3 nomacs raindrop swww visual-studio-code-bin

sudo ln -s /opt/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh
conda config --set auto_activate_base false

# optional --- yay -S galaxybudsclient-bin

# remove Bangla from Manjaro Settings Manager -> Locale

# jetbrains toolbox

# n
# curl -L https://bit.ly/n-install | N_PREFIX=~/.n bash -s -- -y

#fnm
curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
fnm completions --shell zsh

# install the latest version with npm
fnm use --install-if-missing 22

curl -fsSL https://get.pnpm.io/install.sh | sh -
# add ~/.local/share/pnpm/global to the PATH

pnpm install -g neovim tree-sitter-cli

sudo pip3 install patch-ng --break-system-packages

# neovim
LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)
# Would you like to install LunarVim's NodeJS/BunJS dependencies: neovim, tree-sitter-cli?
# [y]es or [n]o (default: no) : y
# Would you like to install LunarVim's Rust dependencies: fd::fd-find, rg::ripgrep?
# [y]es or [n]o (default: no) : y

#
sudo pacman -S hyprland waybar rofi-wayland dunst xdg-desktop-portal-hyprland qt5-wayland qt6-wayland hyprpaper chromium ttf-font-awesome

# sudo pacman -U --noconfirm warp.pkg.tar
# chsh -s $(which zsh)


# [extra] queueing pavucontrol from official arch repo...
# [extra] queueing pamixer from official arch repo...
# [skip] networkmanager is already installed...
# [extra] queueing network-manager-applet from official arch repo...
# [extra] queueing bluez-utils from official arch repo...
# [extra] queueing blueman from official arch repo...
# [extra] queueing brightnessctl from official arch repo...
# [extra] queueing hyprland from official arch repo...
# [extra] queueing dunst from official arch repo...
# [aur] queueing rofi-lbonn-wayland-git from arch user repo...
# [extra] queueing waybar from official arch repo...
# [aur] queueing swaylock-effects-git from arch user repo...
# [aur] queueing wlogout from arch user repo...
# [aur] queueing grimblast-git from arch user repo...
# [aur] queueing hyprpicker from arch user repo...
# [extra] queueing slurp from official arch repo...
# [extra] queueing swappy from official arch repo...
# [extra] queueing cliphist from official arch repo...
# [extra] queueing polkit-gnome from official arch repo...
# [extra] queueing xdg-desktop-portal-hyprland from official arch repo...
# [extra] queueing pacman-contrib from official arch repo...
# [extra] queueing python-pyamdgpuinfo from official arch repo...
# [extra] queueing parallel from official arch repo...
# [extra] queueing jq from official arch repo...
# [skip] imagemagick is already installed...
# [extra] queueing qt5-imageformats from official arch repo...
# [skip] ffmpegthumbs is already installed...
# [skip] kde-cli-tools is already installed...
# [skip] libnotify is already installed...
# [extra] queueing nwg-look from official arch repo...
# [extra] queueing qt5ct from official arch repo...
# [extra] queueing qt6ct from official arch repo...
# [extra] queueing kvantum from official arch repo...
# [extra] queueing kvantum-qt5 from official arch repo...
# [skip] qt5-wayland is already installed...
# [skip] qt6-wayland is already installed...
# [extra] queueing eza from official arch repo...
# [aur] queueing oh-my-zsh-git from arch user repo...
# [aur] queueing zsh-theme-powerlevel10k-git from arch user repo..



# [extract] /home/carmack/.local/share/fonts directory created...
# [extract] Font_CascadiaCove.tar.gz --> /home/carmack/.local/share/fonts...
# [extract] Font_MaterialDesign.tar.gz --> /home/carmack/.local/share/fonts...
# [extract] Font_JetBrainsMono.tar.gz --> /home/carmack/.local/share/fonts...
# [extract] Font_MapleNerd.tar.gz --> /home/carmack/.local/share/fonts...
# [extract] Font_MononokiNerd.tar.gz --> /home/carmack/.local/share/fonts...
# [extract] Font_NotoSansCJK.tar.gz --> /usr/share/fonts...
# [extract] Cursor_BibataIce.tar.gz --> /usr/share/icons...
# [extract] /home/carmack/.icons directory created...
# [extract] Cursor_BibataIce.tar.gz --> /home/carmack/.icons...
# [extract] /home/carmack/.themes directory created...
# [extract] Gtk_Wallbash.tar.gz --> /home/carmack/.themes...
# [fonts] rebuilding font cache...
# [backup] /home/carmack/.zshrc --> /home/carmack/.config/cfg_backups/240702_13h22m56s...
# [preserve] Skipping /home/carmack/.zshrc to preserve user setting...
# [restore] /home/carmack <-- /home/carmack/HyDE/Configs/.p10k.zsh...
# [restore] /home/carmack/.config/Code/User <-- /home/carmack/HyDE/Configs/.config/Code/User/settings.json...
# [restore] /home/carmack/.config/Code - OSS/User <-- /home/carmack/HyDE/Configs/.config/Code - OSS/User/settings.json...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/code-flags.conf...
# [backup] /home/carmack/.config/code-flags.conf --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [preserve] Skipping /home/carmack/.config/code-flags.conf to preserve user setting...
# [backup] /home/carmack/.config/dunst --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/dunst...
# [restore] /home/carmack/.config/hyde <-- /home/carmack/HyDE/Configs/.config/hyde/wallbash...
# [restore] /home/carmack/.config/hypr <-- /home/carmack/HyDE/Configs/.config/hypr/animations.conf...
# [backup] /home/carmack/.config/hypr/hyprland.conf --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config/hypr...
# [restore] /home/carmack/.config/hypr <-- /home/carmack/HyDE/Configs/.config/hypr/hyprland.conf...
# [restore] /home/carmack/.config/hypr <-- /home/carmack/HyDE/Configs/.config/hypr/windowrules.conf...
# [restore] /home/carmack/.config/hypr <-- /home/carmack/HyDE/Configs/.config/hypr/themes...
# [restore] /home/carmack/.config/hypr <-- /home/carmack/HyDE/Configs/.config/hypr/keybindings.conf...
# [restore] /home/carmack/.config/hypr <-- /home/carmack/HyDE/Configs/.config/hypr/monitors.conf...
# [restore] /home/carmack/.config/hypr <-- /home/carmack/HyDE/Configs/.config/hypr/userprefs.conf...
# [restore] /home/carmack/.local/share <-- /home/carmack/HyDE/Configs/.local/share/bin...
# [backup] /home/carmack/.config/kitty --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/kitty...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/Kvantum...
# [skip] /home/carmack/.config/lsd as dependency lsd is not installed...
# [skip] /home/carmack/.config/MangoHud as dependency mangohud is not installed...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/fastfetch...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/qt5ct...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/qt6ct...
# [backup] /home/carmack/.config/rofi --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/rofi...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/swaylock...
# [restore] /home/carmack/.config/waybar <-- /home/carmack/HyDE/Configs/.config/waybar/modules...
# [restore] /home/carmack/.config/waybar <-- /home/carmack/HyDE/Configs/.config/waybar/config.jsonc...
# [backup] /home/carmack/.config/waybar/style.css --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config/waybar...
# [restore] /home/carmack/.config/waybar <-- /home/carmack/HyDE/Configs/.config/waybar/style.css...
# [restore] /home/carmack/.config/waybar <-- /home/carmack/HyDE/Configs/.config/waybar/theme.css...
# [restore] /home/carmack/.config/waybar <-- /home/carmack/HyDE/Configs/.config/waybar/config.ctl...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/wlogout...
# [backup] /home/carmack/.config/xsettingsd --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/xsettingsd...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/nwg-look...
# [backup] /home/carmack/.config/gtk-3.0 --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/gtk-3.0...
# [restore] /home/carmack/.icons <-- /home/carmack/HyDE/Configs/.icons/default...
# [backup] /home/carmack/.gtkrc-2.0 --> /home/carmack/.config/cfg_backups/240702_13h22m56s...
# [restore] /home/carmack <-- /home/carmack/HyDE/Configs/.gtkrc-2.0...
# [backup] /home/carmack/.config/dolphinrc --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/dolphinrc...
# [backup] /home/carmack/.config/kdeglobals --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.config...
# [restore] /home/carmack/.config <-- /home/carmack/HyDE/Configs/.config/kdeglobals...
# [restore] /home/carmack/.config/menus <-- /home/carmack/HyDE/Configs/.config/menus/applications.menu...
# [backup] /home/carmack/.local/share/dolphin --> /home/carmack/.config/cfg_backups/240702_13h22m56s/.local/share...
# [restore] /home/carmack/.local/share <-- /home/carmack/HyDE/Configs/.local/share/dolphin...
# [restore] /home/carmack/.local/share/kxmlgui5 <-- /home/carmack/HyDE/Configs/.local/share/kxmlgui5/dolphin...
# [restore] /home/carmack/.local/share/kio/servicemenus <-- /home/carmack/HyDE/Configs/.local/share/kio/servicemenus/hydewallpaper.desktop...
# [skip] /home/carmack/.config/libinput-gestures.conf as dependency libinput-gestures is not installed...

# [themepatcher] Patching themes...
# 100% 12:0=41s Nordic Blue https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue --skipcaching false